version: "3"

networks:
  external:
    external: true

services:
  reverse-proxy:
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.redis.address=:6379"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=googledomains"
      # - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le.acme.email=washingtonj@diobis.com"
      - "--certificatesresolvers.le.acme.storage=acme.json"
    environment:
      - "GOOGLE_DOMAINS_ACCESS_TOKEN=${GOOGLE_DOMAINS_ACCESS_TOKEN}" 
    ports:
      - "80:80" 
      - "443:443" 
      - "6379:6379"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/acme.json:/acme.json
    networks:
      - external
    # labels: # Dashboard configuration
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.traefik.rule=Host(`admin.diobis.app`) && (PathPrefix(`/traefik`) || PathPrefix(`/api`))"
    #   - "traefik.http.routers.traefik.entrypoints=websecure"
    #   - "traefik.http.routers.traefik.tls.certresolver=le"
    #   - "traefik.http.routers.traefik.service=api@internal"
    #   - "traefik.http.middlewares.dashboardpwd.basicauth.users=${TRAEFIK_DASHBOARD_USERNAME}:${TRAEFIK_DASHBOARD_PASSWORD}"
    #   - "traefik.http.middlewares.traefik-strip.stripprefix.prefixes=/traefik"
    #   - "traefik.http.routers.traefik.middlewares=dashboardpwd,traefik-strip"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --maxmemory 100mb --requirepass ${REDIS_PASSWORD} --maxmemory-policy allkeys-lru
    networks:
      - external
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.redis.entrypoints=redis"
      - "traefik.tcp.routers.redis.tls.certresolver=le"
      - "traefik.tcp.routers.redis.service=redis"
      - "traefik.tcp.services.redis.loadbalancer.server.port=6379"